build_from:
  aarch64: ghcr.io/hassio-addons/base:16.3.6
  amd64: ghcr.io/hassio-addons/base:16.3.6
  armhf: ghcr.io/hassio-addons/base:16.3.6
  armv7: ghcr.io/hassio-addons/base:16.3.6
  i386: ghcr.io/hassio-addons/base:16.3.6
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: rlodev67 add-on"
  org.opencontainers.image.description: "rlodev67 add-on to use as a blueprint for new add-ons."
  org.opencontainers.image.source: "https://github.com/rlodev67/hassio-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  VERSION: "3.5.3.1"
